# Generated by Django 4.0.4 on 2022-06-22 05:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_class', models.CharField(max_length=100)),
                ('billing_code', models.CharField(max_length=20)),
                ('default_rates', models.IntegerField()),
                ('active', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=3)),
            ],
            managers=[
                ('disasterLabor', django.db.models.manager.Manager()),
            ],
        ),
    ]
