# Generated by Django 4.0.4 on 2022-06-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplycode', '0002_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
